name: Deploy FastAPI to Neon Tech (Dilsetrader)

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ensure Python version is correct

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      # Step 4: Verify Installed Packages (Debugging)
      - name: Check installed packages
        run: pip list

      # Step 5: Run tests (if any)
      - name: Run tests
        run: pytest || echo "Tests failed but continuing deployment"

      # Step 6: Install Neon CLI (if not installed)
      - name: Install Neon CLI
        run: |
          curl -fsSL https://neon.tech/install.sh | sh
          export PATH="$HOME/.neon/bin:$PATH"
          echo "$HOME/.neon/bin" >> $GITHUB_PATH

      # Step 7: Verify Neon CLI Installation
      - name: Check Neon CLI version
        run: neon --version || echo "Neon CLI not found"

      # Step 8: Deploy to Neon Tech
      - name: Deploy to Neon Tech (Dilsetrader Project)
        run: |
          neon deploy --project-name Dilsetrader || echo "Deployment failed"
