name: Deploy FastAPI to Neon Tech

on:
  push:
    branches:
      - main  # This triggers deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Change if using a different version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debugging - Check Installed Packages
      - name: Verify Installed Packages
        run: pip list

      # Step 5: Run tests (Fix `pytest` error)
      - name: Run tests
        run: python -m pytest  # Use `python -m pytest` to avoid command not found error

      # Step 6: Deploy to Neon Tech (You may need to customize this step)
      - name: Deploy to Neon Tech
        run: |
          neon-cli deploy --project-name your-project-name  # Customize this based on Neon Tech's deployment method
